# Generated by Django 5.2.3 on 2025-06-27 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livingstone_app', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_day',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birth_month',
        ),
    ]
