# Generated by Django 5.2.3 on 2025-06-28 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livingstone_app', '0003_remove_profile_birth_day_remove_profile_birth_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.CharField(blank=True, choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=10, null=True)),
                ('category', models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('accessories', 'Accessories')], max_length=20)),
                ('subcategory', models.CharField(choices=[('tshirt', 'T-Shirt'), ('wallet', 'Wallet'), ('belt', 'Belt'), ('caps', 'Caps'), ('beer_mug', 'Beer Mug'), ('bag', 'Bag'), ('candles', 'Candles'), ('women_belt', 'Women Belt'), ('accessory_belt', 'Belt'), ('accessory_wallet', 'Wallet'), ('accessory_caps', 'Caps'), ('accessory_candles', 'Candles')], max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('delivery_info', models.TextField(blank=True, null=True)),
                ('payment_info', models.TextField(blank=True, null=True)),
                ('image1', models.ImageField(upload_to='products/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('is_new', models.BooleanField(default=False)),
            ],
        ),
    ]
