# Generated by Django 5.2.3 on 2025-06-28 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livingstone_app', '0004_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('accessories', 'Accessories'), ('home_decor', 'Home Decor')], max_length=20),
        ),
    ]
