# Generated by Django 5.2.3 on 2025-06-28 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livingstone_app', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.CharField(choices=[('tshirt', 'T-Shirt'), ('wallet', 'Wallet'), ('belt', 'Belt'), ('caps', 'Caps'), ('beer_mug', 'Beer Mug'), ('bag', 'Bag'), ('women_belt', 'Women Belt'), ('accessory_belt', 'Belt'), ('accessory_wallet', 'Wallet'), ('accessory_caps', 'Caps'), ('accessory_candles', 'Candles'), ('home_candles', 'Candles')], max_length=30),
        ),
    ]
