# Generated by Django 5.1.6 on 2025-07-08 07:12

import django.db.models.deletion
import django.utils.timezone
import livingstone_app.models
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livingstone_app', '0011_cartitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='availability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='hash',
            field=models.CharField(blank=True, max_length=10000000, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='mihpayid',
            field=models.CharField(blank=True, max_length=10000000, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='order_id',
            field=models.CharField(blank=True, default=None, max_length=10000000, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product_id_number',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=10000000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('accessories', 'Accessories'), ('home_decor', 'Home Decor')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(default=None, max_length=256)),
                ('mobile_number', phonenumber_field.modelfields.PhoneNumberField(help_text='Enter valid contact number with country code', max_length=13, region=None)),
                ('house_no', models.CharField(default=None, max_length=250, verbose_name='House No. / Building Name')),
                ('area', models.CharField(default=None, max_length=250, verbose_name='Road name, Area, Colony')),
                ('landmark', models.CharField(max_length=250)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(choices=[('AN', 'Andaman and Nicobar Islands'), ('AP', 'Andhra Pradesh'), ('AR', 'Arunachal Pradesh'), ('AS', 'Assam'), ('BR', 'Bihar'), ('CG', 'Chhattisgarh'), ('CH', 'Chandigarh'), ('DN', 'Dadra and Nagar Haveli'), ('DD', 'Daman and Diu'), ('DL', 'Delhi'), ('GA', 'Goa'), ('GJ', 'Gujarat'), ('HR', 'Haryana'), ('HP', 'Himachal Pradesh'), ('JK', 'Jammu and Kashmir'), ('JH', 'Jharkhand'), ('KA', 'Karnataka'), ('KL', 'Kerala'), ('LA', 'Ladakh'), ('LD', 'Lakshadweep'), ('MP', 'Madhya Pradesh'), ('MH', 'Maharashtra'), ('MN', 'Manipur'), ('ML', 'Meghalaya'), ('MZ', 'Mizoram'), ('NL', 'Nagaland'), ('OD', 'Odisha'), ('PB', 'Punjab'), ('PY', 'Pondicherry'), ('RJ', 'Rajasthan'), ('SK', 'Sikkim'), ('TN', 'Tamil Nadu'), ('TS', 'Telangana'), ('TR', 'Tripura'), ('UP', 'Uttar Pradesh'), ('UK', 'Uttarakhand'), ('WB', 'West Bengal')], max_length=50)),
                ('pincode', models.IntegerField(validators=[livingstone_app.models.validate_pincode])),
                ('home', models.BooleanField(default=False)),
                ('office', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
