# Generated by Django 5.2.3 on 2025-07-10 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livingstone_app', '0013_placed_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Tracker',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('tracking_id', models.CharField(max_length=90000)),
                ('update_desc', models.CharField(max_length=5000)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('orderInfo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='livingstone_app.placed_order')),
            ],
        ),
    ]
