# Generated by Django 5.1.6 on 2025-07-15 09:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livingstone_app', '0014_order_tracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_tracker',
            name='current_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='placed_order',
            name='label_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='placed_order',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.FloatField(blank=True, default=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='length',
            field=models.FloatField(blank=True, default=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.FloatField(blank=True, default=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.FloatField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name='order_tracker',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order_tracker',
            name='update_desc',
            field=models.TextField(),
        ),
    ]
