# Generated by Django 5.2.3 on 2025-07-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livingstone_app', '0015_order_tracker_current_status_placed_order_label_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_tracker',
            name='label_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order_tracker',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='placed_order',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
