# Generated by Django 5.2.3 on 2025-07-28 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livingstone_app', '0016_order_tracker_label_url_order_tracker_tracking_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayuWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txnid', models.CharField(max_length=1000)),
                ('mihpayid', models.CharField(max_length=1000)),
                ('source', models.CharField(max_length=50)),
                ('payload', models.TextField()),
                ('headers', models.TextField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
