# Generated by Django 5.2.3 on 2025-07-30 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livingstone_app', '0020_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='selected_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='livingstone_app.color'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='selected_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='livingstone_app.size'),
        ),
        migrations.AddField(
            model_name='placed_order',
            name='selected_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='livingstone_app.color'),
        ),
        migrations.AddField(
            model_name='placed_order',
            name='selected_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='livingstone_app.size'),
        ),
        migrations.DeleteModel(
            name='ProductVariant',
        ),
    ]
